### ISSUE TITLE
Signature of datasets

### ISSUE THREAD

**Issue by bjonnh** [w3c/hcls-natural-product-drug-interaction-fair#10]
We need some kind of signature (cryptographic or hash) to make sure a dataset has been downloaded properly or has not been modified (of course some platforms do not allow changes on published data so that reduces the importance of that point on those).

**Comment by rkboyce** [comment]
Added the following to the recommendation "Provide raw data using an open, or at least well-documented, file format":

"The researcher who shares data may want to provide a means for future users of the data to ensure that the dataset has been downloaded properly and has not been modified. To do so, the researcher may generate a signature of the data they are sharing using either cryptographic or hash approaches. The signature of the data can then be shared along with the dataset with instructions on how future users can confirm data integrity."
