### ISSUE TITLE
Use of vector graphics

### ISSUE THREAD

**Issue by bjonnh** [w3c/hcls-natural-product-drug-interaction-fair#11]
In the case images have to be shared, always favor vector graphics ideally in an open and standardized format (such as SVG) or if not possible as PDF (but the format is less standardized and implementations varies outside of the Adobe world)

**Comment by rkboyce** [comment]
Thus great suggestion seems to fit best in the "Publish NMR and spectroscopic results following standards" recommendation. I edited the paragraph that discussed images to start with:

"It is recommended to upload the spectral file as a  vector graphics image, ideally in an open an standardized format such as SVG or, if not possible, as PDF. At a minimum, upload an image with a high resolution." 

The language preserves some other suggested language by Guido.
