### ISSUE TITLE
Enhance the sentence about potential side effects.

### ISSUE THREAD

**Issue by bjonnh** [w3c/hcls-natural-product-drug-interaction-fair#6]
```
   Potential adverse outcomes of NPDIs include transplant rejection,
   cardiovascular collapse, renal and liver toxicity, and death. A review identified 81 NPDIs
    between 35 NPs and 31 drug classes [[Posadzki-2013]].
```

This is almost taken as is from Boyce et al AMIA Annu Symp Proc. 2018; 2018: 279–287.
We should either cite it here (and add quotes) or find references for those assertions.

**Comment by rkboyce** [comment]
I will take this on shortly. I am gathering input from external collaborators and then will do another revision to try and wrap this up.

**Comment by rkboyce** [comment]
I edited these sentences to be more original and added a new citation.
