### ISSUE TITLE
Facilitate editing of the html

### ISSUE THREAD

**Issue by bjonnh** [w3c/hcls-natural-product-drug-interaction-fair#7]
Should we facilitate the editing by:

- [ ]  moving the script with bibliography to the end of the page (it would still work)
- [ ] move the style to a css file
- [ ] move the bibliography in its own js file

**Comment by ericprud** [comment]
This all seems sensible to be and no one's protested. Do you want to submit a PR?

**Comment by bjonnh** [comment]
Yes. Probably by early next week.

**Comment by rkboyce** [comment]
I think this is addressed with my acceptance of the PR. Thanks for the help!
